platform :ios, '10.0'

target 'Visheo' do
  use_frameworks!
  inhibit_all_warnings!
  
  pod 'Fabric'
  pod 'Crashlytics'
  
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  
  pod 'GoogleSignIn'
  
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  
  pod 'MBProgressHUD'
  pod 'Validator'
  
  
  pod 'SDWebImage', '~> 4.0'
end
