platform :ios, '10.0'

use_frameworks!
inhibit_all_warnings!

workspace 'Visheo.xcworkspace'

target 'Visheo' do

  pod 'Fabric'
  pod 'Crashlytics'
  
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  
  pod 'GoogleSignIn'
  
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  
  pod 'MBProgressHUD'
  pod 'Validator'
  
  pod 'SDWebImage', '~> 4.0'
  
  pod 'GPUImage'
  pod 'PryntTrimmerView'
  
   pod 'Reveal-SDK', :configurations => ['Debug']
end

abstract_target 'VisheoVideoFramework' do
	
	project 'Frameworks/visheo/visheo'
	
	pod 'GRDB.swift'
	pod 'lottie-ios', :git => 'https://github.com/nivanchikov/lottie-ios.git'
	pod 'pop'
	pod 'PromiseKit', '~> 4'
	
	target 'visheo' do
	end
	
	target 'VisheoVideo' do
	end
	
end
