platform :ios, '10.0'

use_frameworks!
inhibit_all_warnings!

workspace 'Visheo.xcworkspace'

abstract_target 'App' do

  pod 'Fabric'
  pod 'Crashlytics'
  
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  
  pod 'GoogleSignIn'
  
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  
  pod 'TwitterKit'
  
  pod 'MBProgressHUD'
  pod 'Validator'
  
  pod 'SDWebImage', '~> 4.0'
  pod 'BadgeSwift', '~> 5.0'
  
  pod 'GPUImage'
  pod 'PryntTrimmerView'
  pod 'LGSideMenuController'
  pod 'ReachabilitySwift'
  pod 'SnapKit'
  
  pod 'SwiftyStoreKit'
  
  pod 'Reveal-SDK', :configurations => ['Debug']

  target 'Visheo' do
  end

  target 'VisheoStaging' do
  end
   
end

abstract_target 'VisheoVideoFramework' do
	
	project 'Frameworks/visheo/visheo'
	
	pod 'GRDB.swift'
	pod 'PromiseKit', '~> 4'
	
	target 'visheo' do
	end
	
	target 'VisheoVideo' do
	end
	
end

post_install do |installer|
	installer.pods_project.build_configurations.each do |config|
		config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
	end
end
