default_platform :ios

lane :prebuild do
    plist_name = './VisheoApp/Visheo/Info.plist'
    cocoapods(podfile: "VisheoApp")
    first_build_num = 0
    env_build_number = ENV['XCS_INTEGRATION_NUMBER']
    new_build_number = (first_build_num + env_build_number.to_i).to_s
    set_info_plist_value(
        path: plist_name,
        key: "CFBundleVersion",
        value: new_build_number)

end

lane :postbuild do
    scheme_name = 'Visheo'
    ipa_name = scheme_name + ".ipa"

    gym(
        workspace: "VisheoApp/Visheo.xcworkspace",
        scheme: scheme_name,
        skip_build_archive: true,
        archive_path: ENV['XCS_ARCHIVE'],
        codesigning_identity: 'iPhone Distribution: Olearis TOV (4M6W632NJ7)',
        export_xcargs: "-allowProvisioningUpdates")

    pilot(
        ipa: ipa_name,
        skip_waiting_for_build_processing: true,
        username: 'ogrepet@gmail.com')
end
